### ISSUE TITLE
Was "Instagram" explored as option?

### ISSUE THREAD

**Issue by cmer4** [fluster/web-social-share#1]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
There is no Instagram as option to share to

**Expected behavior:**
There is Instagram as option?

The plugin is real awesome UX, I was wondering if you explored adding Instagram to it?
I suspect I know the answer - Instagram 3rd party dev APIs do not support user friendly sharing path potentially, but still curious if you had explores this?

**Comment by peterpeterparker** [comment]
@cmer4 first of all, thx for the feedback 😃

I wish that it was already possible, that would be so cool, but as far as I understand it is not yet possible because Instagram doesn't expose any web Graph API for that purpose

But, again if I understand correctly, there is hope.  My understanding of https://developers.facebook.com/docs/instagram-api/content-publishing is that Facebook/Instagram are currently working on such an API

**Comment by cmer4** [comment]
Got it. Thank you very much for your answer.  So feels like sometime next year we may have a better API for IG.

**Comment by peterpeterparker** [comment]
@cmer4 finger crossed 😉

**Comment by peterpeterparker** [comment]
Looks like it is has been possible for a while but has now been discontinued. Therefore, unfortunately, I close this feature request.

See this answer on Stackoverflow: https://stackoverflow.com/a/52932285/5404186

**Comment by peterpeterparker** [comment]
If course if in the future it would be possible, ping me!
