### ISSUE TITLE
Queryselector error on some old browser versions

### ISSUE THREAD

**Issue by shanmuga-m** [fluster/web-social-share#25]
Hello team,
Getting below js error on old chrome version browser, while clicking on any social share buttons and while clicking outside to hide the popup.

Uncaught TypeError: Cannot read property 'querySelector' of null e.hide @p-luoh4y63.system.entry.js:1 

It seems those older version browser doesnt contain shadowRoot element which cause this issue.
Please check.

**Comment by peterpeterparker** [comment]
You could try to add the [custom-elements polyfill](https://github.com/webcomponents/polyfills/tree/master/packages/custom-elements) to your build  build, maybe that gonna help

Otherwise not much more I'll do to improve the compatibility with old old browsers, I'm fine with the current behavior of the component.
