### ISSUE TITLE
there is an Angular standard version

### ISSUE THREAD

**Issue by cervelliriccardo** [fluster/web-social-share#36]
Hi,
I like your component. don't you have an angular module version, without the stencil framework?

**Comment by peterpeterparker** [comment]
Happy to hear you like the component :)

Well actually no need of "Angular standard or module version" or whatsoever.

Because the component is a Web Component, developed with the help of the compiler [Stencil](https://stenciljs.com), it is already compatible with or without any modern frameworks.

Means it can be use, out of the box, in Angular, React, VueJS etc. or even without any frameworks, respectively with vanilla JavaScript.

Summarized: you can already use the component in Angular.

Hope this answer your question.
